language: ruby
rvm:
  - 2.0.0
env: SECRET_KEY_BASE=0c316f7380f1d63ab0138afa943f3785c4e038eb11d096fed94ffc09f0536c5787155fc60663ee0c81c7433ab06dbb6fd51fc51fb76e1fd7c74a6c5159984abd
before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo cp /etc/postgresql/9.1/main/pg_hba.conf ./
  - sudo apt-get remove postgresql postgresql-9.1 -qq --purge
  - source /etc/lsb-release
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ $DISTRIB_CODENAME-pgdg main" > pgdg.list
  - sudo mv pgdg.list /etc/apt/sources.list.d/
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install postgresql-9.2 postgresql-contrib-9.2 -qq
  - sudo /etc/init.d/postgresql stop
  - sudo mv ./pg_hba.conf /etc/postgresql/9.2/main
  - sudo /etc/init.d/postgresql start
  - cp config/database.travis.yml config/database.yml
  - psql -c 'CREATE DATABASE ember_watch_test;' -U postgres
script:
 - bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: |-
      YkaljlEM36hJn742G6yTg9BgTlX1Mn1rrNp6wUpqDrT1TotiD6YpA4qx0Df4
      jd8G297XyH2fquxSucOAD6Vw9973w17cY0Nyyen/wpkGHeO9KKzdcx2f9epI
      UVSp2s2a1cPtLQ/ab1XFqbFZKl+bzKrbYgOLMkCc+CVUtx37Hr8=
  run: "rake db:migrate"
